/**
 * Runtime configuration for the client, resolved from Vite environment
 * variables with sensible localhost defaults for development.
 *
 * `window.SERVER_URL` (set by `client/public/env-config.js`, generated by
 * `startup.sh`) takes priority when present: it lets the same built
 * bundle be opened from another device on the LAN or over a tunnel (e.g.
 * a phone) and still reach the right server, instead of resolving
 * `localhost` to that device itself.
 */

const SERVER_PORT = import.meta.env.VITE_SERVER_PORT || 5001;

const runtimeServerUrl = typeof window !== 'undefined' ? window.SERVER_URL : undefined;

/** Base URL of the backend server (protocol + host + port), no path suffix. */
export const SERVER_URL = runtimeServerUrl || import.meta.env.VITE_SERVER_URL || 'http://localhost:' + SERVER_PORT;

/** Base URL for REST API requests, i.e. {@link SERVER_URL} plus the `/api` prefix. */
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || `${SERVER_URL}/api`

export default API_BASE_URL;