services:
  - type: web_service
    name: shareandcopy-server
    env: docker
    branch: main
    dockerfilePath: server/Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: PORT
        value: "5001"
  - type: static_site
    name: shareandcopy-client
    env: node
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    autoDeploy: true
    plan: starter
    envVars:
      - key: VITE_SERVER_URL
        value: "https://shareandcopy-server.onrender.com"
